import UniversalCardExamples from '@/shared/components/examples/universal-card-examples';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {


  return (
    <div className='h-screen flex items-center justify-center'>
      <UniversalCardExamples />
    </div>
  );
}
